### PR TITLE
fix: update image manager

### LINKED ISSUE #2434: [bug] Adding favicon and/or social share images breaks the app
Steps to replicate: 

1. Open project
2. Open project settings
3. Add social share featured image OR favicon
4. React error appears: 
```
Runtime Error
Server


TypeError: "/1500x500.jpg" cannot be parsed as a URL against "[object Object]"

Call Stack
17

Hide 15 ignore-listed frame(s)
resolveErrorDev
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1858:46)
getOutlinedModel
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1342:22)
parseModelString
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1482:15)
Object.<anonymous>
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (2287:18)
JSON.parse
<anonymous> (0:0)
initializeModelChunk
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1047:26)
getOutlinedModel
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1320:11)
parseModelString
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1533:15)
Object.<anonymous>
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (2287:18)
JSON.parse
<anonymous> (0:0)
initializeModelChunk
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (1047:26)
ReactPromise.then
node_modules/next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-client.browser.development.js (2548:11)
trackUsedThenable
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (5032:22)
useThenable
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (6876:18)
Object.use
node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js (6891:55)
exports.use
node_modules/next/dist/compiled/react/cjs/react.development.js (1163:34)
BrowserResolvedMetadata
node_modules/next/src/client/components/metadata/browser-resolved-metadata.tsx (9:34)
```

### PR DESCRIPTION
**Pull request by spartan-vutrannguyen**
## Related Issues

fixes #2434
## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Release
- [ ] Refactor
- [ ] Other (please describe):

## Screenshots (if applicable)

1. Create folder and upload image to it

https://github.com/user-attachments/assets/85207256-3a21-4f34-a98c-0fae1942b715

2. Rename/Delete images

https://github.com/user-attachments/assets/92bf785b-d35c-4245-8c70-1c513c726a51

3. Move image between folder - Move folder to folder

https://github.com/user-attachments/assets/1b5e3961-99ea-4149-bbd9-20a35897875a

4. Rename/Delete folder 

https://github.com/user-attachments/assets/6d28159b-51fd-49cf-9c8a-27fb04b41bd9

https://github.com/user-attachments/assets/403a23c8-645e-48b5-9a0d-b38d96f51362

## Additional Notes

----

> [!IMPORTANT]
> Refactor image manager and components to use new folder context for improved image and folder operations.
> 
>   - **Behavior**:
>     - Refactor `DeleteImageModal`, `FolderDropdownMenu`, `FolderList`, `FolderTab`, `Folder`, `FolderCreateModal`, `FolderDeleteModal`, `FolderMoveModal`, `FolderRenameModal`, `ImageDropdownMenu`, `ImageItem`, `ImageList`, `ImagesTab`, `MoveImageModal`, `RenameImageModal` to use new folder context.
>     - Add `useFolderContext` in `folder-provider.tsx` for folder operations (create, rename, delete, move).
>     - Update `ImageManager` in `image/index.ts` to handle image operations with new path generation logic.
>   - **Models**:
>     - Update `FolderNode` in `folder.ts` to remove `images` and `children` properties.
>     - Add `SandboxDirectory` type in `files.ts`.
>   - **Utility**:
>     - Update `isImageFile()` in `file.ts` to use `getMimeType()`.
>     - Add `ensureImageFolderPrefix()` in `folder.ts`.
>     - Remove unused functions from `folder.ts`.
>   - **Testing**:
>     - Update tests in `file.test.ts` to cover new image file handling logic.
>     - Remove `use-folder.test.ts` as it is no longer relevant.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=onlook-dev%2Fonlook&utm_source=github&utm_medium=referral)<sup> for 0c4a99fc2dfe07410f98cad38fd2ba130152b81a. You can [customize](https://app.ellipsis.dev/onlook-dev/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: packages/models/src/sandbox/files.ts [hunk 1]
```diff
@@ -15,3 +15,9 @@ export interface BinarySandboxFile extends BaseSandboxFile {
 }
 
 export type SandboxFile = TextSandboxFile | BinarySandboxFile;
+
+export type SandboxDirectory = {
+    type: 'directory';
+    path: string;
+    files: SandboxFile[];
```
Comment (Kitenite) [inline packages/models/src/sandbox/files.ts]: We should not store files object here, same issue we talk about with synching. At best it stores a path but let's not have it until we need it

File: apps/web/client/src/components/store/editor/sandbox/index.ts [hunk 2]
```diff
@@ -427,7 +467,7 @@ export class SandboxManager {
                         continue;
                     }
                     const cachedFile = this.fileSync.readCache(normalizedPath);
-                    if (!cachedFile || cachedFile.content === null || cachedFile.content !== content.content) {
+                    if (!cachedFile?.content || cachedFile.content !== content.content) {
```
Comment (Kitenite) [inline apps/web/client/src/components/store/editor/sandbox/index.ts]: This will trigger if content is '' empty string

File: apps/web/client/src/app/project/[id]/_components/left-panel/image-tab/rename-modal.tsx [hunk 3]
```diff
@@ -9,48 +9,41 @@ import {
...
-        isOpen: boolean;
-        toggleOpen: () => void;
-        onRename: (newName: string) => void;
-        newName: string;
-        isLoading?: boolean;
-    }) => {
-        const handleRename = () => {
-            if (!isLoading) {
-                onRename(newName);
+export const RenameImageModal = observer(
```
Comment (Kitenite) [inline apps/web/client/src/app/project/[id]/_components/left-panel/image-tab/rename-modal.tsx]: I don't think this needs to be an observer?
