### PR TITLE
fix text color changes inconsistently when entering edit mode

### LINKED ISSUE #1725: [bug][elements] Text color changes inconsistently when entering edit mode
#### Describe the bug
**Summary:**
The text color behaves inconsistently when entering edit mode. The color is black when double-clicked but changes to white when the Enter key is used to enter edit mode.

**Step to reproduce:**
1. Create a text element with content "Hello".
2. Double-click the text to enter edit mode.
3. Observe the text color.
4. Press Enter to edit the text instead.
5. Observe the text color again.

**Actual result:**
- When using double-click, the text appears black in edit mode.
- When pressing Enter, the text appears white in edit mode.
- Please watch this video: 
https://github.com/user-attachments/assets/527abe2b-8a3a-4a19-9b63-7eb5752e0d96

**Expected result:**
The text color should remain consistent in edit mode, regardless of whether it is accessed via double-click or Enter.

### PR DESCRIPTION
**Pull request by spartan-vutrannguyen**
## Description

- Fix text color changes inconsistently when entering edit mode
Root cause:
- The `DOUBLE_CLICK` action uses the `getElementAtLoc` function, which already passes `true` to include the `styles` object.  
- The `ENTER` action uses `getDomElementByDomId`, but it still needs to pass `true` to retrieve the `styles` object as well.

## Related Issues

- fixes #1725 
## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Release
- [ ] Refactor
- [ ] Other (please describe):

## Screenshots (if applicable)

https://github.com/user-attachments/assets/821c020e-90e8-4ddd-ade9-27da9c1b1380

## Additional Notes

----

> [!IMPORTANT]
> Fix inconsistent text color change in edit mode by updating `getDomElementByDomId` call and handling null URLs in `Image.tsx`.
> 
>   - **Behavior**:
>     - Fix inconsistent text color change when entering edit mode by modifying `getDomElementByDomId` call in `index.ts` to include an additional parameter.
>     - Ensure `setSelectedImage(null)` is called in `Image.tsx` when no URL is provided.
>   - **Files**:
>     - `index.ts`: Update `getDomElementByDomId` call to include `true` parameter.
>     - `Image.tsx`: Add `else` block to set `selectedImage` to `null` when `url` is not provided.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=onlook-dev%2Fonlook&utm_source=github&utm_medium=referral)<sup> for c4e1f3ee943dd957572233c4fa021914a833cfe1. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: apps/studio/src/components/Modals/Settings/Site/Image.tsx [hunk 1]
```diff
@@ -29,6 +29,8 @@ const ImagePicker = forwardRef<
             if (image) {
                 setSelectedImage(image.content);
             }
+        } else {
```
Comment (spartan-vutrannguyen) [inline apps/studio/src/components/Modals/Settings/Site/Image.tsx:32]: Small fix for Metadata.
