### PR TITLE
fix: handle src/app, src/pages

### LINKED ISSUE #2203: [bug] Need to properly handle src/app
#### Describe the bug
We're currently running under the assumption that the project is under app/ but nextjs can have src/app as an alternative configuration. This pattern breaks a lot of assumptions in the sandbox, font handling, etc.

### PR DESCRIPTION
**Pull request by irfanfaraaz**
## Description
This pull request enhances font configuration handling in the Next.js project by updating the following files to support both ```src/``` and ```non-src/``` directory structures:

```@index.ts```: Enhanced the detectRouterType() method to check both ['src/app', 'app'] and ['src/pages', 'pages'] paths.
```@inject.ts```: Modified the logic to check for layout files in both possible paths.
```@remove.ts```: Modified the logic to check for layout files in both possible paths.

## Related Issues
Fixes #2203 

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Release
- [ ] Refactor
- [ ] Other (please describe):

## Screenshots (if applicable)

image

image

## Additional Notes

----

> [!IMPORTANT]
> Enhances layout file handling in `inject.ts` and `remove.ts` to support `src/app` and `app` directories, and updates `FontManager` in `index.ts` for dynamic font config path detection.
> 
>   - **Behavior**:
>     - `injectBuiltWithScript()` and `removeBuiltWithScriptFromLayout()` in `inject.ts` and `remove.ts` now check both `src/app` and `app` directories for layout files.
>     - `FontManager` in `index.ts` dynamically sets `fontConfigPath` based on detected router type, supporting `src/app`, `app`, `src/pages`, and `pages`.
>   - **Misc**:
>     - Updates to `bun.lock` with dependency changes.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=onlook-dev%2Fonlook&utm_source=github&utm_medium=referral)<sup> for 290af258138f6ee4d4eefb7214976502483a9084. You can [customize](https://app.ellipsis.dev/onlook-dev/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by Rudra-Sankha-Sinhamahapatra — COMMENTED** [review]
Hii @irfanfaraaz can you provide a ss or screen recording that src folder next js app is running

**Comment by irfanfaraaz** [comment]
Hii! @Rudra-Sankha-Sinhamahapatra @Kitenite 

I’ve added a few tests to validate the router detection. Here’s a brief summary of what the tests cover:

In ```inject.test.ts```:
1) Check if injectBuiltWithScript and removeBuiltWithScriptFromLayout work with the src/app directory structure.

In ```router-detection.test.ts```:
	2) Detects app router: Validates detection for both app/ and src/app/ directories.
	3) Prioritization: Ensures that src/app/ is prioritized over app/ when both contain layout files.
	4) Detects pages router: Validates detection for both pages/ and src/pages/ directories
	5) Default behavior: Checks that the function defaults to the app router when no files are present.
	6) Prioritization of app over pages: Validates that the app router is prioritized when both are present.
	
The reason src/app/ is prioritized over app/ is because of the order in the array: 

	```const APP_ROUTER_PATHS = ['src/app', 'app'];```

This means the function will return the result for src/app first if both directories contain layout files.

**Comment by irfanfaraaz** [comment]
Forgot to mention, to test the font I created a mock sandbox to simulate the file system.

File: packages/growth/src/remove.ts [hunk 1]
```diff
@@ -11,12 +11,26 @@ export async function removeBuiltWithScriptFromLayout(
...
+            const exists = await fileOps.fileExists(path);
+            if (exists) {
+                layoutPath = path;
+                break;
+            }
+        }
 
-        if (!layoutExists) {
-            console.error('Layout file not found at', layoutPath);
+        if (!layoutPath) {
```
Comment (Kitenite) [inline packages/growth/src/remove.ts:16]: Much cleaner, thanks @irfanfaraaz !
